config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  delete 'notifications/index', to:'notifications#delete_all'
  delete 'home/index', to:'home#delete_all_user_posts'
  delete 'keywords/index', to:'keywords#delete_all_user_keywords'
  resources :posts
  resources :keywords
  devise_for :users
  root 'home#index'
  get 'home/my_posts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates :word, presence: true, uniqueness: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post
  belongs_to :recipient, class_name: "User"
  belongs_to :poster, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :neighborhood, presence: true

  after_commit :send_notifications, on: :create

  def send_notifications
    FindNotifiableUsersJob.perform_later(self)
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :keyword

  after_commit :destroy_unreferenced_keywords, on: :destroy
  validate :has_less_than_maximum_allowed_keywords

  def destroy_unreferenced_keywords
  	DestroyUnreferencedKeywordsJob.perform_later(self.keyword_id);
  end

  def has_less_than_maximum_allowed_keywords
  	if User.find(self.user_id).keywords.size >= Rails.configuration.max_keywords_per_user
  		errors.add("cannot have more than #{Rails.configuration.max_keywords_per_user} keywords!")
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions, dependent: :destroy
  has_many :keywords, through: :subscriptions
  has_many :posts, dependent: :destroy
  has_many :notifications, dependent: :destroy, foreign_key: :recipient_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
  end

  def my_posts
  	@posts = current_user.posts.order("created_at DESC").page(params[:page])
  end

  def delete_all_user_posts
   	@posts = current_user.posts
   	@posts.destroy_all
   	respond_to do |format|
      format.html { redirect_to home_my_posts_path, notice: "성공적으로 삭제되었습니다." }
      format.json { head :no_content }
    end
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /keywords or /keywords.json
  def index
    @keywords = current_user.keywords.order("created_at DESC").page(params[:page])
  end

  # GET /keywords/1 or /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords or /keywords.json
  def create
    @keyword = Keyword.find_or_create_by(keyword_params)

    respond_to do |format|
      if @keyword.save
        current_user.keywords << @keyword
        format.html { redirect_to keywords_url, notice: "키워드 등록되었습니다." }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1 or /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to keywords_url, notice: "Keyword was successfully updated." }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1 or /keywords/1.json
  def destroy
    current_user.keywords.destroy(@keyword)
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: "성공적으로 삭제되었습니다." }
      format.json { head :no_content }
    end
  end

  def delete_all_user_keywords
    current_user.keywords.destroy_all
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: "성공적으로 삭제되었습니다." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyword_params
      params.require(:keyword).permit(:word)
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_action :authenticate_user!
	
  def index
   	@notifications = current_user.notifications.order("created_at DESC").page(params[:page])

   	# Mark all notifications on page as 'read' when user opens notification index
   	@notifications.each do |notification|
   		notification.update(read: true)
   	end
  end

  def delete_all
   	@notifications = current_user.notifications
   	@notifications.destroy_all
   	respond_to do |format|
      format.html { redirect_to notifications_index_path, notice: "성공적으로 삭제되었습니다." }
      format.json { head :no_content }
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.order("created_at DESC").page(params[:page])
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "게시글 성공적으로 올렸습니다." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

    # notification sent after commit (See post model)
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "게시글 성공적으로 수정되었습니다." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to home_my_posts_path, notice: "성공적으로 삭제되었습니다." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :neighborhood, :category, :price, :body, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Haangn Market', root_path, class:"nav-link" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to '중고거래', posts_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
        
          <li class="nav-item">
            <%= link_to '나의 판매내역', home_my_posts_path, class:"nav-link" %>
          </li>        
          <li class="nav-item">
            <%= link_to '키워드 알림 설정', keywords_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "새로운 키워드 알림 #{current_user.notifications.where(read: false).count}개", notifications_index_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '프로필 설정', edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to '로그인', new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '가입하기', new_user_registration_path, class:"nav-link" %>
          </li>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h2>Haangn Market에 오신 것을 환영합니다!</h2>
<br/>
<h6>

   안녕하세요! 당근마켓 코딩 과제 "Haangn Market"을 작성한 Hannah Hertzog (헤르트쪼그 하나)라고 합니다.</br>
   여기 Heroku 환경에서 테스트 하실 수 있습니다.
   <br/><br/><br/>
   1. 브라우저에서 https://hanngnmarket.herokuapp.com/ 사이트 열고 "abc@123.com" 으로 가입 (다른 이메일도 가능합니다) <br/>
   2. 비밀창에서 https://hanngnmarket.herokuapp.com/ 열고 "def@456.com"으로 가입<br/>
   3. 2개의 프로필에서 키워드 몇개 등록<br/>
   4. 등록한 키워드가 1개 이상 포함된 게시글 올리기 (본인 게시글 알림은 본인 프로필에 뜨지 않습니다)<br/>
   5. 원하시는 대로 테스트하기
   <br/><br/><br/>
   저의 어플리케이션과 코드를 봐주셔서 감사합니다 ^^<br/>
   좋은 하루 보내세요! 

</h6>

app/views/home/my_posts.html.erb
<h2>나의 판매내역</h2>

<%= link_to '새 게시글', new_post_path, class:"btn btn-outline-success" %>
<%= link_to '전체 삭제', home_index_path, method: :delete, data: { confirm: '정말로 판매내역을 전체 삭제하고 싶으세요?' }, class:"btn btn-outline-danger" %>
<br/><br/>

<table class="table table-hover table-light">
  <thead>
    <tr>
      <th></th>
      <th><strong>제목</strong></th>
      <th>동네</th>
      <th>카테고리</th>
      <th>가격</th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to '보기', post, class:"btn btn-outline-primary" %></td>
        <td><strong><%= post.title %></strong></td>
        <td><%= post.neighborhood %></td>
        <td><%= post.category %></td>
        <td>
           <% if post.price != nil %>
            <%= "#{post.price}원" %>
          <% end %>
        </td>
        <td><%= post.body %></td>

        <td><%= link_to '수정', edit_post_path(post), class:"btn btn-outline-success" %></td>
        <td><%= link_to '삭제', post, method: :delete, data: { confirm: '정말로 이 게시글을 삭제하고 싶으세요?' }, class:"btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @posts %>

<br>

app/views/keywords/_form.html.erb
<% if current_user.keywords.size < Rails.configuration.max_keywords_per_user %>

  <%= form_with(model: keyword) do |form| %>
    <% if keyword.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(keyword.errors.count, "error") %> 에러 때문에 키워드 저장 실패했습니다:</h2>

        <ul>
          <% keyword.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="form-group col-lg-2">
        <%= form.text_field :word, class:"form-control", placeholder:"키워드를 입력해주세요." %>
      </div>
    </div>

    <div class="field">
      <%= form.number_field :user_id, id: :keyword_user_id, class:"form-control", value:current_user.id, type: :hidden %>
    </div>
    <br/>

    <div class="actions">
      <%= form.submit class:"btn btn-outline-success", value:"등록" %>
    </div>
  <% end %>

<% else %>

  <p>키워드는 <%= Rails.configuration.max_keywords_per_user %>개까지만 지정하실 수 있어요ㅠ 다른 키워드를 삭제해주세요!</p>

<% end %>

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h2>키워드 알림 설정</h2>

<br/>
<h5>알림 받을 키워드 <%= current_user.keywords.size %> / <%= Rails.configuration.max_keywords_per_user %></h5>

<% if current_user.keywords.size < Rails.configuration.max_keywords_per_user %>
	<%= link_to '새 키워드 등록', new_keyword_path, class:"btn btn-outline-success" %>
<% end %>
<%= link_to '키워드 전체 삭제', keywords_index_path, method: :delete, data: { confirm: '정말로 모든 키워드를 삭제하고 싶으세요?' }, class:"btn btn-outline-danger" %>
<br/><br/>

<table class="table table-hover table-light">

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><h5><%= keyword.word %></h5></td>
        <td><%= link_to '삭제', keyword, method: :delete, data: { confirm: '정말로 이 키워드를 삭제하고 싶으세요?' }, class:"btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<%= paginate @keywords %>

<br>

app/views/keywords/new.html.erb
<h4>새 키워드 등록</h4>
<br/>

<%= render 'form', keyword: @keyword %>

app/views/keywords/show.html.erb
<% if user_signed_in? && (@keyword.user_id == current_user.id) %>
	<p>
	  <strong>Word:</strong>
	  <%= @keyword.word %>
	</p>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Haangnmarket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <br/>

    <div class="container">

      <% if notice %>
        <br/>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/notifications/index.html.erb
<h2>키워드 알림</h2>

<%= link_to "전체 삭제", notifications_index_path, method: :delete, data: { confirm: '정말로 키워드 알림 전체 삭제하고 싶으세요?' }, class:"btn btn-outline-danger" %>
<br/><br/>


<table class="table table-hover table-light">
  <thead>
    <tr>
      <th></th>
      <th><strong>제목</strong></th>
      <th>동네</th>
      <th>카테고리</th>
      <th>가격</th>
      <th></th>
      <th>키워드</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        
	      <td><%= link_to '보기', notification.post, class:"btn btn-outline-primary" %></td>
	      <td><strong><%= notification.post.title %></strong></td>
	      <td><%= notification.post.neighborhood %></td>
	      <td><%= notification.post.category %></td>
	      <td>
	        <% if notification.post.price != nil %>
	          <%= "#{notification.post.price}원" %>
	        <% end %>
	      </td>
	      <td><%= notification.post.body %></td>
	      <td><%= notification.keyword %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @notifications %>

<br>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> 에러 때문에 게시글 올리기 실패했습니다:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :title, class:"form-control", placeholder:"글 제목 (필수사항)" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :neighborhood, class:"form-control", placeholder:"동네 (필수사항)" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :category, class:"form-control", placeholder:"카테고리 (선택사항)" %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :price, class:"form-control", placeholder:"₩ 가격 (선택사항)" %>
  </div>

  <div class="field mb-3">
    <%= form.text_area :body, class:"form-control", placeholder:"이 동네에 올릴 게시글 내용을 작성해주세요! (선택사항)", rows: 5 %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :post_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-outline-success", value:"완료" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% if user_signed_in? && (@post.user_id == current_user.id) %>
	<h4>게시글 수정하기</h4>

	<%= render 'form', post: @post %>

<% end %>

app/views/posts/index.html.erb
<h2>중고거래</h2>

<% if user_signed_in? %>
  <%= link_to '새 게시글', new_post_path, class:"btn btn-outline-success" %>
  <br/><br/>
<% end %>

<table class="table table-hover table-light">
  <thead>
    <tr>
      <th></th>
      <th><strong>제목</strong></th>
      <th>동네</th>
      <th>카테고리</th>
      <th>가격</th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>

        <td><%= link_to '보기', post, class:"btn btn-outline-primary" %></td>
        <td><strong><%= post.title %></strong></td>
        <td><%= post.neighborhood %></td>
        <td><%= post.category %></td>
        <td>
          <% if post.price != nil %>
            <%= "#{post.price}원" %>
          <% end %>
        </td>
        <td><%= post.body %></td>

        <!-- allow user to edit/delete posts that they own on "All Posts" page-->
        <% if user_signed_in? && (post.user_id == current_user.id) %>
          <td><%= link_to '수정', edit_post_path(post), class:"btn btn-outline-success" %></td>
          <td><%= link_to '삭제', post, method: :delete, data: { confirm: '정말로 이 게시글을 삭제하고 싶으세요?' }, class:"btn btn-outline-danger" %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @posts %>

<br>

app/views/posts/new.html.erb
<h4>새 게시글</h4>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="card text-center">
  <div class="card-header">
    <strong><h3><%= @post.title %></h3></strong>
  </div>
  
  <div class="card-body">
    <h4 class="card-title">
      <% if @post.category != "" %>
        <%= @post.category %>  -  
      <% end %>
      <%= @post.neighborhood %>
    </h4>

    <% if @post.body != "" %>
      <h5 class="card-text"><br/><%= @post.body %><br/></h5>
    <% end %>
  </div>

  <% if user_signed_in? && (@post.user_id == current_user.id) %>
    <div class="d-grid gap-1 col-1 mx-auto">
      <%= link_to '수정', edit_post_path(@post), class:"btn btn-outline-success" %>
      <br/>
    </div>
  <% end %>

  <% if @post.price != nil %>
    <div class="card-footer text-muted">
      <strong><h5><%= @post.price %>원</h5></strong>
    </div>
  <% end %>
</div>